-- Supabase-compatible SQL for benhvientaman
-- This file removes MySQL-specific syntax and can be imported into PostgreSQL / Supabase.
-- This version is safe to run multiple times on the same database.
-- WARNING: This script will reset the schema and data for the tables below.

BEGIN;

DROP TABLE IF EXISTS auth_tokens CASCADE;
DROP TABLE IF EXISTS thongtinsuckhoe CASCADE;
DROP TABLE IF EXISTS lichlamviec CASCADE;
DROP TABLE IF EXISTS donthuoc CASCADE;
DROP TABLE IF EXISTS chitietdichvukham CASCADE;
DROP TABLE IF EXISTS lichkham CASCADE;
DROP TABLE IF EXISTS benhnhan CASCADE;
DROP TABLE IF EXISTS bacsi CASCADE;
DROP TABLE IF EXISTS nguoidung CASCADE;
DROP TABLE IF EXISTS danhmucthuoc CASCADE;
DROP TABLE IF EXISTS danhmucdichvu CASCADE;
DROP TABLE IF EXISTS chuyenkhoa CASCADE;

CREATE TABLE auth_tokens (
    TokenID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID integer NOT NULL,
    Selector varchar(255) NOT NULL UNIQUE,
    ValidatorHash varchar(255) NOT NULL,
    ExpiresAt timestamp NOT NULL
);

CREATE TABLE chuyenkhoa (
    ChuyenKhoaID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChuyenKhoa varchar(100) NOT NULL UNIQUE,
    MoTa text
);

CREATE TABLE danhmucdichvu (
    DichVuID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDichVu varchar(255) NOT NULL UNIQUE,
    MoTa text,
    DonGia numeric(15,2) NOT NULL DEFAULT 0,
    HoatDong boolean DEFAULT true
);

CREATE TABLE danhmucthuoc (
    ThuocID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenThuoc varchar(255) NOT NULL UNIQUE,
    HoatChat varchar(255),
    DonViTinh varchar(50) NOT NULL
);

CREATE TABLE nguoidung (
    UserID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen varchar(100) NOT NULL,
    Email varchar(100) NOT NULL UNIQUE,
    MatKhau varchar(255) NOT NULL,
    SoDienThoai varchar(15) UNIQUE,
    VaiTro varchar(20) NOT NULL DEFAULT 'BenhNhan',
    NgayTao timestamp DEFAULT CURRENT_TIMESTAMP,
    HoatDong boolean DEFAULT true
);

CREATE TABLE bacsi (
    BacSiID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID integer NOT NULL UNIQUE,
    ChuyenKhoaID integer,
    MoTa text,
    KinhNghiem varchar(255),
    CONSTRAINT fk_bacsi_user FOREIGN KEY (UserID) REFERENCES nguoidung(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_bacsi_chuyenkhoa FOREIGN KEY (ChuyenKhoaID) REFERENCES chuyenkhoa(ChuyenKhoaID) ON DELETE SET NULL
);

CREATE TABLE benhnhan (
    BenhNhanID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID integer UNIQUE,
    HoTen varchar(100) NOT NULL,
    NgaySinh date,
    GioiTinh varchar(10),
    SoDienThoai varchar(15) NOT NULL,
    DiaChi varchar(255),
    NgayTaoHoSo timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_benhnhan_user FOREIGN KEY (UserID) REFERENCES nguoidung(UserID) ON DELETE SET NULL
);

CREATE TABLE lichkham (
    LichKhamID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BacSiID integer NOT NULL,
    BenhNhanID integer NOT NULL,
    ThoiGianKham timestamp NOT NULL,
    TrangThai varchar(20) NOT NULL DEFAULT 'ChoXacNhan',
    LyDoKham text,
    GhiChuCuaBacSi text,
    NgayDatLich timestamp DEFAULT CURRENT_TIMESTAMP,
    TrieuChung text,
    ChuanDoan text,
    PhacDoDieuTri text,
    LoiDanKeDon text,
    NgayTaiKham date,
    CONSTRAINT fk_lichkham_bacsi FOREIGN KEY (BacSiID) REFERENCES bacsi(BacSiID) ON DELETE CASCADE,
    CONSTRAINT fk_lichkham_benhnhan FOREIGN KEY (BenhNhanID) REFERENCES benhnhan(BenhNhanID) ON DELETE CASCADE
);

CREATE TABLE chitietdichvukham (
    ChiTietID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LichKhamID integer NOT NULL,
    DichVuID integer NOT NULL,
    SoLuong integer NOT NULL DEFAULT 1,
    DonGiaTaiThoiDiem numeric(15,2) NOT NULL,
    GhiChu text,
    CONSTRAINT fk_chitietdv_lichkham FOREIGN KEY (LichKhamID) REFERENCES lichkham(LichKhamID) ON DELETE CASCADE,
    CONSTRAINT fk_chitietdv_danhmuc FOREIGN KEY (DichVuID) REFERENCES danhmucdichvu(DichVuID)
);

CREATE TABLE donthuoc (
    DonThuocID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LichKhamID integer NOT NULL,
    ThuocID integer NOT NULL,
    SoLuong integer NOT NULL,
    HuongDanSuDung varchar(255) NOT NULL,
    CONSTRAINT fk_donthuoc_lichkham FOREIGN KEY (LichKhamID) REFERENCES lichkham(LichKhamID) ON DELETE CASCADE,
    CONSTRAINT fk_donthuoc_danhmuc FOREIGN KEY (ThuocID) REFERENCES danhmucthuoc(ThuocID)
);

CREATE TABLE lichlamviec (
    LichLamViecID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BacSiID integer NOT NULL,
    NgayTrongTuan integer NOT NULL,
    GioBatDau time NOT NULL,
    GioKetThuc time NOT NULL,
    CONSTRAINT fk_lichlamviec_bacsi FOREIGN KEY (BacSiID) REFERENCES bacsi(BacSiID) ON DELETE CASCADE,
    UNIQUE (BacSiID, NgayTrongTuan, GioBatDau)
);

CREATE TABLE thongtinsuckhoe (
    ThongTinID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BenhNhanID integer NOT NULL,
    Loai varchar(50) NOT NULL,
    MoTa varchar(255) NOT NULL,
    GhiChu text,
    CONSTRAINT fk_thongtinsuckhoe_benhnhan FOREIGN KEY (BenhNhanID) REFERENCES benhnhan(BenhNhanID) ON DELETE CASCADE
);

CREATE INDEX idx_auth_tokens_user ON auth_tokens(UserID);
CREATE INDEX idx_lichkham_bacsi_thoigian ON lichkham(BacSiID, ThoiGianKham);
CREATE INDEX idx_lichkham_benhnhan_thoigian ON lichkham(BenhNhanID, ThoiGianKham);
CREATE INDEX idx_chitietdv_lichkham ON chitietdichvukham(LichKhamID);
CREATE INDEX idx_chitietdv_danhmuc ON chitietdichvukham(DichVuID);
CREATE INDEX idx_donthuoc_lichkham ON donthuoc(LichKhamID);
CREATE INDEX idx_donthuoc_danhmuc ON donthuoc(ThuocID);
CREATE INDEX idx_benhnhan_sdt ON benhnhan(SoDienThoai);
CREATE INDEX idx_thongtinsuckhoe_benhnhan ON thongtinsuckhoe(BenhNhanID);

INSERT INTO chuyenkhoa (ChuyenKhoaID, TenChuyenKhoa, MoTa) VALUES
(1, 'Nội tổng quát', 'Chẩn đoán và điều trị các bệnh nội khoa tổng quát.'),
(2, 'Ngoại tổng quát', 'Phẫu thuật điều trị các bệnh ngoại khoa phổ biến.'),
(3, 'Nhi khoa', 'Khám và điều trị bệnh lý trẻ em.'),
(4, 'Sản phụ khoa', 'Chăm sóc sức khỏe phụ nữ, thai sản.'),
(5, 'Tim mạch', 'Chẩn đoán và điều trị các bệnh tim mạch.'),
(6, 'Da liễu', 'Điều trị các bệnh về da và thẩm mỹ da.'),
(7, 'Tai Mũi Họng', 'Khám và điều trị các bệnh tai, mũi, họng.'),
(8, 'Răng Hàm Mặt', 'Chăm sóc răng miệng và phẫu thuật hàm mặt.'),
(9, 'Mắt', 'Khám và điều trị các bệnh về mắt.'),
(10, 'Thần kinh', 'Khám và điều trị các bệnh lý thần kinh.'),
(11, 'Ung bướu', 'Chẩn đoán và điều trị ung thư, khối u.'),
(12, 'Hô hấp', 'Khám và điều trị bệnh lý phổi và hô hấp.'),
(13, 'Tiêu hóa', 'Khám và điều trị bệnh dạ dày, ruột và gan.'),
(14, 'Thận - Tiết niệu', 'Điều trị bệnh thận và đường tiết niệu.'),
(15, 'Nội tiết', 'Chẩn đoán và điều trị bệnh lý nội tiết như tiểu đường.'),
(16, 'Chấn thương chỉnh hình', 'Phẫu thuật và điều trị xương khớp, chấn thương.'),
(17, 'Phục hồi chức năng', 'Hỗ trợ hồi phục chức năng vận động.'),
(18, 'Huyết học', 'Chẩn đoán và điều trị bệnh máu.'),
(19, 'Dinh dưỡng', 'Tư vấn chế độ ăn và dinh dưỡng.'),
(20, 'Nội soi', 'Dịch vụ nội soi tiêu hóa và hô hấp.'),
(21, 'Lão khoa', 'Khám và chăm sóc sức khỏe người cao tuổi.'),
(22, 'Tâm thần', 'Chẩn đoán và điều trị rối loạn tâm thần.'),
(23, 'Miễn dịch - Dị ứng', 'Chẩn đoán và điều trị dị ứng và rối loạn miễn dịch.'),
(24, 'Phong - Da liễu', 'Điều trị bệnh da liễu và bệnh phong.'),
(25, 'Hồi sức cấp cứu', 'Cấp cứu và chăm sóc bệnh nhân nặng.'),
(26, 'Gây mê hồi sức', 'Hỗ trợ gây mê và hồi tỉnh sau phẫu thuật.'),
(27, 'Chẩn đoán hình ảnh', 'Chụp X-quang, MRI, CT.'),
(28, 'Xét nghiệm y học', 'Phòng xét nghiệm y học lâm sàng.'),
(29, 'Y học cổ truyền', 'Điều trị bằng thuốc Nam, châm cứu.'),
(30, 'Sức khỏe sinh sản', 'Tư vấn và chăm sóc sức khỏe sinh sản.');

INSERT INTO danhmucdichvu (DichVuID, TenDichVu, MoTa, DonGia, HoatDong) VALUES
(1, 'Khám tổng quát', 'Khám sức khỏe tổng quát, tư vấn bệnh lý và đặt lịch theo dõi.', 150000.00, true),
(2, 'Khám tim mạch', 'Khám và đánh giá bệnh tim mạch, huyết áp, nhịp tim.', 200000.00, true),
(3, 'Khám da liễu', 'Khám và điều trị các bệnh da liễu cơ bản.', 180000.00, true),
(4, 'Khám tiêu hóa', 'Khám bệnh đường tiêu hóa, đầy đủ triệu chứng và điều trị hỗ trợ.', 170000.00, true),
(5, 'Khám mắt', 'Khám mắt tổng quát, đo thị lực và tư vấn điều trị.', 160000.00, true),
(6, 'Xét nghiệm máu cơ bản', 'Xét nghiệm cơ bản để hỗ trợ chẩn đoán nhanh.', 250000.00, true),
(7, 'Siêu âm', 'Siêu âm cơ bản cho các cơ quan nội tạng.', 300000.00, true);

INSERT INTO danhmucthuoc (ThuocID, TenThuoc, HoatChat, DonViTinh) VALUES
(1, 'Paracetamol 500mg', 'Paracetamol', 'Viên'),
(2, 'Amoxicillin 500mg', 'Amoxicillin', 'Viên'),
(3, 'Ibuprofen 400mg', 'Ibuprofen', 'Viên'),
(4, 'Cefixime 100mg', 'Cefixime', 'Viên'),
(5, 'Vitamin C 500mg', 'Acid Ascorbic', 'Viên'),
(6, 'Clorpheniramin 4mg', 'Chlorpheniramine', 'Viên'),
(7, 'Omeprazole 20mg', 'Omeprazole', 'Viên'),
(8, 'Metformin 500mg', 'Metformin', 'Viên'),
(9, 'Amlodipine 5mg', 'Amlodipine', 'Viên'),
(10, 'Losartan 50mg', 'Losartan', 'Viên'),
(11, 'Furosemide 40mg', 'Furosemide', 'Viên'),
(12, 'Enalapril 10mg', 'Enalapril', 'Viên'),
(13, 'Simvastatin 20mg', 'Simvastatin', 'Viên'),
(14, 'Atorvastatin 10mg', 'Atorvastatin', 'Viên'),
(15, 'Prednisolone 5mg', 'Prednisolone', 'Viên'),
(16, 'Dexamethasone 0.5mg', 'Dexamethasone', 'Viên'),
(17, 'Azithromycin 250mg', 'Azithromycin', 'Viên'),
(18, 'Ciprofloxacin 500mg', 'Ciprofloxacin', 'Viên'),
(19, 'Clindamycin 300mg', 'Clindamycin', 'Viên'),
(20, 'Loperamide 2mg', 'Loperamide', 'Viên'),
(21, 'Salbutamol 2mg', 'Salbutamol', 'Viên'),
(22, 'Cetirizine 10mg', 'Cetirizine', 'Viên'),
(23, 'Loratadine 10mg', 'Loratadine', 'Viên'),
(24, 'Ranitidine 150mg', 'Ranitidine', 'Viên'),
(25, 'Pantoprazole 40mg', 'Pantoprazole', 'Viên'),
(26, 'Esomeprazole 20mg', 'Esomeprazole', 'Viên'),
(27, 'Alprazolam 0.5mg', 'Alprazolam', 'Viên'),
(28, 'Diazepam 5mg', 'Diazepam', 'Viên'),
(29, 'Domperidone 10mg', 'Domperidone', 'Viên'),
(30, 'Spiramycin 3MIU', 'Spiramycin', 'Viên'),
(31, 'Rifampicin 300mg', 'Rifampicin', 'Viên'),
(32, 'Isoniazid 300mg', 'Isoniazid', 'Viên'),
(33, 'Pyrazinamide 500mg', 'Pyrazinamide', 'Viên'),
(34, 'Ethambutol 400mg', 'Ethambutol', 'Viên'),
(35, 'Methotrexate 2.5mg', 'Methotrexate', 'Viên'),
(36, 'Allopurinol 100mg', 'Allopurinol', 'Viên'),
(37, 'Colchicine 0.5mg', 'Colchicine', 'Viên'),
(38, 'Levothyroxine 50mcg', 'Levothyroxine', 'Viên'),
(39, 'Carbimazole 5mg', 'Carbimazole', 'Viên'),
(40, 'Glimepiride 2mg', 'Glimepiride', 'Viên'),
(41, 'Gliclazide 30mg', 'Gliclazide', 'Viên'),
(42, 'Pioglitazone 15mg', 'Pioglitazone', 'Viên'),
(43, 'Sitagliptin 50mg', 'Sitagliptin', 'Viên'),
(44, 'Linagliptin 5mg', 'Linagliptin', 'Viên'),
(45, 'Bisoprolol 5mg', 'Bisoprolol', 'Viên'),
(46, 'Metoprolol 50mg', 'Metoprolol', 'Viên'),
(47, 'Propranolol 40mg', 'Propranolol', 'Viên'),
(48, 'Verapamil 80mg', 'Verapamil', 'Viên'),
(49, 'Diltiazem 60mg', 'Diltiazem', 'Viên'),
(50, 'Nitroglycerin 2.6mg', 'Nitroglycerin', 'Viên'),
(51, 'Warfarin 2mg', 'Warfarin', 'Viên'),
(52, 'Aspirin 81mg', 'Acetylsalicylic Acid', 'Viên'),
(53, 'Clopidogrel 75mg', 'Clopidogrel', 'Viên'),
(54, 'Dabigatran 110mg', 'Dabigatran', 'Viên'),
(55, 'Rivaroxaban 10mg', 'Rivaroxaban', 'Viên'),
(56, 'Apixaban 5mg', 'Apixaban', 'Viên'),
(57, 'Rosuvastatin 10mg', 'Rosuvastatin', 'Viên'),
(58, 'Hydrochlorothiazide 25mg', 'Hydrochlorothiazide', 'Viên'),
(59, 'Spironolactone 25mg', 'Spironolactone', 'Viên'),
(60, 'Indapamide 1.5mg', 'Indapamide', 'Viên'),
(61, 'Telmisartan 40mg', 'Telmisartan', 'Viên'),
(62, 'Valsartan 80mg', 'Valsartan', 'Viên'),
(63, 'Olmesartan 20mg', 'Olmesartan', 'Viên'),
(64, 'Ramipril 5mg', 'Ramipril', 'Viên'),
(65, 'Perindopril 4mg', 'Perindopril', 'Viên'),
(66, 'Candesartan 8mg', 'Candesartan', 'Viên'),
(67, 'Irbesartan 150mg', 'Irbesartan', 'Viên'),
(68, 'Trimetazidine 20mg', 'Trimetazidine', 'Viên'),
(69, 'Ivabradine 5mg', 'Ivabradine', 'Viên'),
(70, 'Digoxin 0.25mg', 'Digoxin', 'Viên'),
(71, 'Folic Acid 5mg', 'Folic Acid', 'Viên'),
(72, 'Ferrous Sulfate 200mg', 'Ferrous Sulfate', 'Viên'),
(73, 'Cyanocobalamin 500mcg', 'Vitamin B12', 'Viên'),
(74, 'Thiamine 100mg', 'Vitamin B1', 'Viên'),
(75, 'Pyridoxine 50mg', 'Vitamin B6', 'Viên'),
(76, 'Calcium Carbonate 500mg', 'Calcium Carbonate', 'Viên'),
(77, 'Cholecalciferol 1000IU', 'Vitamin D3', 'Viên'),
(78, 'Magnesium Oxide 250mg', 'Magnesium Oxide', 'Viên'),
(79, 'Zinc Sulfate 50mg', 'Zinc Sulfate', 'Viên'),
(80, 'Ascorbic Acid 500mg', 'Vitamin C', 'Viên'),
(81, 'Alpha Tocopherol 400IU', 'Vitamin E', 'Viên'),
(82, 'Riboflavin 10mg', 'Vitamin B2', 'Viên'),
(83, 'Nicotinamide 100mg', 'Vitamin B3', 'Viên'),
(84, 'Biotin 500mcg', 'Biotin', 'Viên'),
(85, 'Pantothenic Acid 100mg', 'Vitamin B5', 'Viên'),
(86, 'Levocetirizine 5mg', 'Levocetirizine', 'Viên'),
(87, 'Montelukast 10mg', 'Montelukast', 'Viên'),
(88, 'Ketotifen 1mg', 'Ketotifen', 'Viên'),
(89, 'Mebendazole 500mg', 'Mebendazole', 'Viên'),
(90, 'Albendazole 400mg', 'Albendazole', 'Viên'),
(91, 'Doxycycline 100mg', 'Doxycycline', 'Viên'),
(92, 'Minocycline 100mg', 'Minocycline', 'Viên'),
(93, 'Erythromycin 250mg', 'Erythromycin', 'Viên'),
(94, 'Levofloxacin 500mg', 'Levofloxacin', 'Viên'),
(95, 'Moxifloxacin 400mg', 'Moxifloxacin', 'Viên'),
(96, 'Linezolid 600mg', 'Linezolid', 'Viên'),
(97, 'Vancomycin 500mg', 'Vancomycin', 'Viên'),
(98, 'Meropenem 500mg', 'Meropenem', 'Viên'),
(99, 'Imipenem 500mg', 'Imipenem', 'Viên'),
(100, 'Ceftriaxone 1g', 'Ceftriaxone', 'Viên');

INSERT INTO nguoidung (UserID, HoTen, Email, MatKhau, SoDienThoai, VaiTro, NgayTao, HoatDong) VALUES
(1, 'taman', 'taman@gmail.com', '12341234', '0346861038', 'BacSi', '2025-07-05 10:28:12', true),
(2, 'Lê Đạt', 'ledat3@gmail.com', '12341234', '0333876785', 'BacSi', '2025-07-05 11:31:09', true),
(4, 'benh nhan', 'benhnhan1@gmail.com', '12341234', '0123456789', 'BenhNhan', '2025-07-05 12:13:58', true),
(5, 'Admin', 'admin@gmail.com', '$2y$10$uRsri5JFN.f2Z2zRrouLqeXFTTEsAlyQgqdTGuqmSuyutfWBmQvX2', '0346861035', 'QuanTri', '2025-07-06 14:04:13', true),
(6, 'Nguyễn Văn A', 'nguyenvana@gmail.com', '12341234', '0346861036', 'BenhNhan', '2025-07-06 17:37:39', true);

INSERT INTO bacsi (BacSiID, UserID, ChuyenKhoaID, MoTa, KinhNghiem) VALUES
(1, 2, 5, '', '10 năm kinh nghiệm trong lĩnh vực Tim mạch'),
(2, 1, 27, NULL, NULL);

INSERT INTO benhnhan (BenhNhanID, UserID, HoTen, NgaySinh, GioiTinh, SoDienThoai, DiaChi, NgayTaoHoSo) VALUES
(1, 2, 'Trương Công Ước', NULL, NULL, '0333876785', NULL, '2025-07-05 11:31:09'),
(2, 4, 'benh nhan', '1999-07-22', 'Nữ', '0123456789', 'Giáp Bát, Hà Nội', '2025-07-05 12:13:58'),
(3, 5, 'Admin', NULL, NULL, '0346861035', NULL, '2025-07-06 14:04:13'),
(4, 6, 'Nguyễn Văn A', '2008-06-04', 'Nam', '0346861036', NULL, '2025-07-06 17:37:39'),
(5, NULL, 'Nguyễn Thị A', '2006-11-23', 'Nữ', '0346861037', NULL, '2025-07-06 21:09:00');

INSERT INTO lichkham (LichKhamID, BacSiID, BenhNhanID, ThoiGianKham, TrangThai, LyDoKham, GhiChuCuaBacSi, NgayDatLich, TrieuChung, ChuanDoan, PhacDoDieuTri, LoiDanKeDon, NgayTaiKham) VALUES
(1, 1, 2, '2025-07-06 08:00:00', 'DaHoanThanh', 'Khám tổng quát', '', '2025-07-05 22:15:30', 'Mệt mỏi nhẹ', 'Bình thường', '', NULL, '2025-07-24'),
(2, 1, 2, '2025-07-07 09:30:00', 'ChoXacNhan', 'Khám tim mạch', NULL, '2025-07-05 22:15:30', 'Đau ngực, hồi hộp', NULL, NULL, NULL, NULL),
(3, 1, 2, '2025-07-08 14:00:00', 'DaHoanThanh', 'Khám da liễu', '', '2025-07-05 22:15:30', 'Nổi mẩn đỏ', 'Bình thường\r\n', '', NULL, NULL),
(4, 1, 2, '2025-07-09 10:15:00', 'DaHoanThanh', 'Khám tiêu hóa', '', '2025-07-05 22:15:30', 'Đau bụng âm ỉ', 'Bình thường', '', NULL, '2025-07-10'),
(5, 1, 2, '2025-07-10 16:00:00', 'DaHoanThanh', 'Khám mắt', 'Không bỏ lượt uống', '2025-07-05 22:15:30', 'Nhìn mờ, chảy nước mắt', '', '', NULL, '2025-07-31'),
(6, 1, 2, '2025-07-07 15:00:00', 'ChoXacNhan', 'Kiểm tra tổng quát', NULL, '2025-07-06 12:55:34', NULL, NULL, NULL, NULL, NULL);

INSERT INTO chitietdichvukham (ChiTietID, LichKhamID, DichVuID, SoLuong, DonGiaTaiThoiDiem, GhiChu) VALUES
(1, 1, 1, 1, 100000.00, NULL),
(2, 2, 2, 1, 150000.00, NULL),
(3, 3, 3, 1, 120000.00, NULL),
(4, 4, 4, 1, 180000.00, NULL),
(5, 5, 5, 1, 200000.00, NULL);

INSERT INTO donthuoc (DonThuocID, LichKhamID, ThuocID, SoLuong, HuongDanSuDung) VALUES
(1, 5, 48, 5, 'uống sau ăn sáng'),
(2, 5, 52, 20, 'uống sau ăn trưa'),
(3, 5, 84, 10, 'uống sau ăn tối'),
(4, 4, 76, 100, ''),
(5, 1, 17, 50, ''),
(6, 3, 17, 50, '');

INSERT INTO lichlamviec (LichLamViecID, BacSiID, NgayTrongTuan, GioBatDau, GioKetThuc) VALUES
(1, 1, 1, '07:00:00', '17:00:00');

INSERT INTO thongtinsuckhoe (ThongTinID, BenhNhanID, Loai, MoTa, GhiChu) VALUES
(1, 2, 'Tiền sử bệnh', 'Dị ứng với penicillin, Đã phẫu thuật ruột thừ năm 2010', NULL);

INSERT INTO auth_tokens (TokenID, UserID, Selector, ValidatorHash, ExpiresAt) VALUES
(1, 1, 'selector_1', 'validator_hash_1', '2026-12-31 23:59:59');

ALTER TABLE auth_tokens
    ADD CONSTRAINT fk_authtokens_user FOREIGN KEY (UserID) REFERENCES nguoidung(UserID) ON DELETE CASCADE;

COMMIT;
