services:
  - type: web
    name: benhvientaman-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://frontend-benhvientaman.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
