-- Phiếu yêu cầu đặt lịch linh hoạt cho khách chưa chọn đủ lịch khám.
-- Migration an toàn: chỉ tạo bảng/index mới, không thay đổi hoặc xóa dữ liệu lichkham.

BEGIN;

CREATE TABLE IF NOT EXISTS yeucaudatlich (
    yeucauid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid integer NULL REFERENCES nguoidung(userid) ON DELETE SET NULL,
    hoten varchar(100) NOT NULL,
    sodienthoai varchar(20) NOT NULL,
    email varchar(100) NULL,
    chuyenkhoaid integer NULL REFERENCES chuyenkhoa(chuyenkhoaid) ON DELETE SET NULL,
    dichvuid integer NULL REFERENCES danhmucdichvu(dichvuid) ON DELETE SET NULL,
    bacsiid integer NULL REFERENCES bacsi(bacsiid) ON DELETE SET NULL,
    ngaymongmuon date NULL,
    giomongmuon time NULL,
    lydokham text NULL,
    ghichu text NULL,
    trangthai varchar(30) NOT NULL DEFAULT 'ChoLienHe',
    ngaytao timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lichkhamid integer NULL REFERENCES lichkham(lichkhamid) ON DELETE SET NULL,
    CONSTRAINT ck_yeucaudatlich_status CHECK (trangthai IN ('ChoLienHe', 'DangXuLy', 'DaXacNhan', 'DaChuyenThanhLichKham', 'DaHuy'))
);

-- Keep an already-created request table compatible with the booking API.
ALTER TABLE yeucaudatlich ADD COLUMN IF NOT EXISTS phibacsitaithoidiem numeric(15,2);
ALTER TABLE yeucaudatlich ADD COLUMN IF NOT EXISTS phidichvutaithoidiem numeric(15,2);
ALTER TABLE yeucaudatlich ADD COLUMN IF NOT EXISTS tongtamtinh numeric(15,2);

-- Add the expected foreign keys when this migration is applied to an older
-- request table that existed before the booking flow was introduced.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_yeucaudatlich_user'
           AND conrelid = 'yeucaudatlich'::regclass
    ) THEN
        ALTER TABLE yeucaudatlich
            ADD CONSTRAINT fk_yeucaudatlich_user
            FOREIGN KEY (userid) REFERENCES nguoidung(userid) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_yeucaudatlich_specialty'
           AND conrelid = 'yeucaudatlich'::regclass
    ) THEN
        ALTER TABLE yeucaudatlich
            ADD CONSTRAINT fk_yeucaudatlich_specialty
            FOREIGN KEY (chuyenkhoaid) REFERENCES chuyenkhoa(chuyenkhoaid) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_yeucaudatlich_service'
           AND conrelid = 'yeucaudatlich'::regclass
    ) THEN
        ALTER TABLE yeucaudatlich
            ADD CONSTRAINT fk_yeucaudatlich_service
            FOREIGN KEY (dichvuid) REFERENCES danhmucdichvu(dichvuid) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_yeucaudatlich_doctor'
           AND conrelid = 'yeucaudatlich'::regclass
    ) THEN
        ALTER TABLE yeucaudatlich
            ADD CONSTRAINT fk_yeucaudatlich_doctor
            FOREIGN KEY (bacsiid) REFERENCES bacsi(bacsiid) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'fk_yeucaudatlich_appointment'
           AND conrelid = 'yeucaudatlich'::regclass
    ) THEN
        ALTER TABLE yeucaudatlich
            ADD CONSTRAINT fk_yeucaudatlich_appointment
            FOREIGN KEY (lichkhamid) REFERENCES lichkham(lichkhamid) ON DELETE SET NULL;
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_status_time
    ON yeucaudatlich(trangthai, ngaytao DESC);
CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_user
    ON yeucaudatlich(userid);
CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_phone
    ON yeucaudatlich(sodienthoai);
CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_doctor
    ON yeucaudatlich(bacsiid);
CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_specialty
    ON yeucaudatlich(chuyenkhoaid);

COMMIT;
