-- Phiếu yêu cầu đặt lịch linh hoạt cho khách chưa chọn đủ lịch khám.
-- Migration an toàn: chỉ tạo bảng/index mới, không thay đổi hoặc xóa dữ liệu lichkham.

BEGIN;

CREATE TABLE IF NOT EXISTS yeucaudatlich (
    yeucauid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid integer NULL REFERENCES nguoidung(userid) ON DELETE SET NULL,
    hoten varchar(100) NOT NULL,
    sodienthoai varchar(20) NOT NULL,
    email varchar(100) NULL,
    chuyenkhoaid integer NULL REFERENCES chuyenkhoa(chuyenkhoaid) ON DELETE SET NULL,
    dichvuid integer NULL REFERENCES danhmucdichvu(dichvuid) ON DELETE SET NULL,
    bacsiid integer NULL REFERENCES bacsi(bacsiid) ON DELETE SET NULL,
    ngaymongmuon date NULL,
    giomongmuon time NULL,
    lydokham text NULL,
    ghichu text NULL,
    trangthai varchar(30) NOT NULL DEFAULT 'ChoLienHe',
    ngaytao timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lichkhamid integer NULL REFERENCES lichkham(lichkhamid) ON DELETE SET NULL,
    CONSTRAINT ck_yeucaudatlich_status CHECK (trangthai IN ('ChoLienHe', 'DangXuLy', 'DaXacNhan', 'DaChuyenThanhLichKham', 'DaHuy'))
);

CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_status_time
    ON yeucaudatlich(trangthai, ngaytao DESC);
CREATE INDEX IF NOT EXISTS idx_yeucaudatlich_user
    ON yeucaudatlich(userid);

COMMIT;
