-- Thông báo nội bộ cho tài khoản quản trị.
-- Có thể chạy nhiều lần trên Supabase/PostgreSQL.

BEGIN;

ALTER TABLE benhnhan
    ADD COLUMN IF NOT EXISTS email varchar(100);

CREATE TABLE IF NOT EXISTS thongbao (
    thongbaoid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid integer NOT NULL REFERENCES nguoidung(userid) ON DELETE CASCADE,
    lichkhamid integer REFERENCES lichkham(lichkhamid) ON DELETE SET NULL,
    loai varchar(50) NOT NULL DEFAULT 'SYSTEM',
    tieude varchar(200) NOT NULL,
    noidung text NOT NULL,
    dadoc boolean NOT NULL DEFAULT false,
    ngaydoc timestamp NULL,
    ngaytao timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_thongbao_user_unread
    ON thongbao(userid, dadoc, ngaytao DESC);
CREATE INDEX IF NOT EXISTS idx_thongbao_lichkham
    ON thongbao(lichkhamid);

CREATE OR REPLACE FUNCTION fn_notify_admin_new_user()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO thongbao (userid, loai, tieude, noidung)
    SELECT admin.userid,
           'NEW_USER',
           'Tài khoản mới đăng ký',
           format('Tài khoản %s (%s) vừa được tạo với vai trò %s.',
                  COALESCE(NEW.hoten, 'Chưa cập nhật'),
                  COALESCE(NEW.email, 'không có email'),
                  COALESCE(NEW.vaitro, 'Chưa phân loại'))
    FROM nguoidung admin
    WHERE lower(COALESCE(admin.vaitro, '')) IN
          ('quantri', 'quantrivien', 'quanly', 'admin', 'administrator')
      AND COALESCE(admin.hoatdong, true) = true;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_notify_admin_new_appointment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    patient_name text;
    patient_email text;
BEGIN
    SELECT COALESCE(bn.hoten, pu.hoten, 'Khách hàng'),
           COALESCE(bn.email, pu.email, 'không có email')
      INTO patient_name, patient_email
      FROM benhnhan bn
      LEFT JOIN nguoidung pu ON pu.userid = bn.userid
     WHERE bn.benhnhanid = NEW.benhnhanid;

    INSERT INTO thongbao (userid, lichkhamid, loai, tieude, noidung)
    SELECT admin.userid,
           NEW.lichkhamid,
           'NEW_APPOINTMENT',
           'Có lịch khám mới',
           format('Người bệnh %s (%s) đã đặt lịch khám vào %s. Lý do: %s',
                  patient_name,
                  patient_email,
                  to_char(NEW.thoigiankham, 'DD/MM/YYYY HH24:MI'),
                  COALESCE(NULLIF(NEW.lydokham, ''), 'Chưa cung cấp'))
    FROM nguoidung admin
    WHERE lower(COALESCE(admin.vaitro, '')) IN
          ('quantri', 'quantrivien', 'quanly', 'admin', 'administrator')
      AND COALESCE(admin.hoatdong, true) = true;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_admin_new_user ON nguoidung;
CREATE TRIGGER trg_notify_admin_new_user
AFTER INSERT ON nguoidung
FOR EACH ROW
EXECUTE FUNCTION fn_notify_admin_new_user();

DROP TRIGGER IF EXISTS trg_notify_admin_new_appointment ON lichkham;
CREATE TRIGGER trg_notify_admin_new_appointment
AFTER INSERT ON lichkham
FOR EACH ROW
EXECUTE FUNCTION fn_notify_admin_new_appointment();

COMMIT;
